media:
  input: images
  output: /images
content:
  - name: months
    label: Months (Journal)
    type: collection
    path: _posts
    format: yaml-frontmatter
    filename:
      template: "{year}-{month}-{day}-{primary}.md"
      field: create
    view:
      fields: [title, date]
      primary: title
    operations:
      rename: false
      delete: false
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
      - name: permalink
        label: Public URL (e.g. /akai-mono/)
        type: string
        required: true
      - name: layout
        label: Layout
        type: string
        default: default
      - name: body
        label: Article
        type: rich-text
